version: 2.1

executors:
  go:
    working_directory: ~/app
    docker:
      - image: cimg/go:1.16
    resource_class: small

jobs:
  setup:
    executor: go
    steps:
      - checkout
      - run:
          name: download
          command: make mod
  test:
    executor: go
    steps:
      - checkout
      - run:
          name: lint
          command: make lint
      - run:
          name: test
          command: make test

workflows:
  version: 2
  run:
    jobs:
      - setup
      - test:
          requires:
            - setup