name: Run lint and test

on:
  push:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.17"
      - name: lint
        run: make lint
      - name: test
        run: make test